Check for documentRangeFormatting in FormatExpr
Range formatting support is required for FormatExpr to work, but the
function currently only checks if document formatting is supported,
resulting in an error using gq when range format not supported:

    Error: request textDocument/rangeFormatting failed (Method not found: textDocument/rangeFormatting, error = MethodNotFound)

Fix by adding check for range formatting and using in FormatExpr()

Note: this is a breaking change, previously with formatexpr set to
lsp#lsp#FormatExpr(), using gq would result in no change to the selected
range if document formatting was supported but range formatting was not,
now it will fallback to Vim's internal format mechanism (you could call
this a bug fix though, I think that's how it was intended to work).