Add some tests for <plug>(LspFormat) mappings
Two simple tests added for plug mappings, these tests do not test that
only specific ranges of the buffer were formatted as I could not get
clangd to actually perform range formatting, even though it says it is
supported. This is not an issue with the mappings, :{range}LspFormat
also applies to the entire file rather than the specified range.

The operator function has been changed to a script local function and
then referenced using <ScriptCmd> to ensure it is available to call from
within a vim9script function, otherwise the following error occurs:

Error: Test Test_LspFormat_PlugMappings() failed with exception Vim(eval):E117: Unknown function: LspFormatFunc at command line..script <path-to-lsp>/test/runner.vim[51]..function <SNR>1_LspRunTests[23]..Test_LspFormat_PlugMappings, line 6